language: node_js
node_js: "6"

before_script: npm install grunt-cli -g

script: npm run test

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
